/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { UniswapV2, UniswapV2Interface } from "../UniswapV2";

const _abi = [
  "function getAmountsIn(uint256,address[]) view returns (uint256[])",
  "function getAmountsOut(uint256,address[]) view returns (uint256[])",
  "function swapExactETHForTokens(uint256,address[],address,uint256) returns (uint256[])",
  "function swapExactTokensForTokens(uint256,uint256,address[],address,uint256) returns (uint256[])",
];

export class UniswapV2__factory {
  static readonly abi = _abi;
  static createInterface(): UniswapV2Interface {
    return new utils.Interface(_abi) as UniswapV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UniswapV2 {
    return new Contract(address, _abi, signerOrProvider) as UniswapV2;
  }
}
